{
  try {
    cache("LON",0).put("k","v");
    fail("This should have thrown an exception");
  }
 catch (  Exception e) {
  }
  assertNull(cache("LON",0).get("k"));
  assertNull(cache("LON",1).get("k"));
  assertNull(backup("LON").get("k"));
  assertEquals(0,txTable(cache("LON",0)).getLocalTransactions().size());
  assertEquals(0,txTable(cache("LON",1)).getLocalTransactions().size());
  assertEquals(0,txTable(backup("LON")).getLocalTransactions().size());
}
