{
  try {
    handler.handle(new Callback[]{callback});
  }
 catch (  SaslException e) {
    throw e;
  }
catch (  IOException e) {
    throw new SaslException("Failed to authenticate due to callback exception",e);
  }
catch (  UnsupportedCallbackException e) {
    throw new SaslException("Failed to authenticate due to unsupported callback",e);
  }
}
