{
  try {
    if (cleanup == CleanupPhase.AFTER_TEST)     teardown();
  }
 catch (  Exception e) {
    log.error("Unexpected!",e);
  }
}
