{
  log.error("Failing because of exception",e);
  fail(e.toString());
}
