{
  try {
    future.get(timeout,unit);
  }
 catch (  TimeoutException e) {
    throw new Exception("task timed out",e);
  }
catch (  InterruptedException e) {
    Thread.currentThread().interrupt();
    if (trace)     log.trace("task was interrupted");
  }
 finally {
    future.cancel(true);
  }
}
