{
  assertException(wrapperExceptionClass,t);
  assertException(exceptionClass,messageRegex,t.getCause());
}
