{
  Throwable exception=null;
  try {
    runnable.run();
  }
 catch (  Throwable t) {
    exception=t;
  }
  return exception;
}
