{
  try {
    state.waitForStart();
  }
 catch (  InterruptedException e1) {
    state.errorManage(e1);
    return;
  }
  try {
    beforeLoop();
  }
 catch (  IOException e) {
    log.error("unexpected error",e);
    state.errorManage(e);
  }
  while (!state.needToQuit()) {
    try {
      testLoop();
    }
 catch (    Exception e) {
      log.error("unexpected error",e);
      state.errorManage(e);
    }
  }
  try {
    cleanup();
  }
 catch (  IOException e) {
    log.error("unexpected error",e);
    state.errorManage(e);
  }
}
