{
  log.debugf("Sending %s to self",future);
  try {
    Callable<Object> call=new Callable<Object>(){
      @Override public Object call() throws Exception {
        Object result=null;
        future.getCommand().init(cache);
        try {
          result=future.getCommand().perform(null);
          return Collections.singletonMap(rpc.getAddress(),new SuccessfulResponse(result));
        }
 catch (        Throwable e) {
          return e;
        }
 finally {
          future.notifyDone();
        }
      }
    }
;
    final FutureTask<Object> task=new FutureTask<Object>(call);
    future.setNetworkFuture((Future<T>)task);
    localExecutorService.submit(task);
  }
 catch (  Throwable e1) {
    log.localExecutionFailed(e1);
  }
}
