{
  if (isFailing) {
    putFailed=true;
    throw new CacheException("Induced failure");
  }
 else {
    return invokeNextInterceptor(ctx,command);
  }
}
